# Generated by Django 4.1.5 on 2023-02-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='cart_wishlist',
            new_name='wishlist',
        ),
    ]
